const $=(id)=>document.getElementById(id);
const heuristicSchemas={default:(t)=>toJsonDefault(t),task:(t)=>toJsonTask(t),cvjd:(t)=>toJsonCvJd(t)};
function toJsonDefault(text){const f=extractFields(text);const p={schema:"default",title:f.title||"",role:f.role||"",task:f.task||"",inputs:f.inputs||[],constraints:f.constraints||[],tone:f.tone||"",style:f.style||"",output_format:f.output_format||"",prompt:text.trim()};return JSON.stringify(p,null,2)}
function toJsonTask(text){const f=extractFields(text);const p={schema:"task",system:f.role||"",objective:f.task||f.objective||"",steps:f.steps||[],data:f.inputs||[],deliverables:f.deliverables||f.output||"",guardrails:f.constraints||[],examples:f.examples||[],prompt:text.trim()};return JSON.stringify(p,null,2)}
function toJsonCvJd(text){const f=extractFields(text);const p={schema:"cvjd",role:"Copywriting Analyst & AI Text Humanizer",goal:"Evaluate CV vs JD; find alignment, gaps, rewrites.",inputs:{cv:f.cv||"",jd:f.jd||"",extras:f.inputs||[]},criteria:["alignment","gaps","keywords","tone","rewrite"],prompt:text.trim()};return JSON.stringify(p,null,2)}
function extractFields(text){const lines=text.split(/\r?\n/);const out={inputs:[],constraints:[],steps:[],examples:[]};let current=null;const setField=(k,v)=>{if(Array.isArray(out[k])) out[k].push(v.trim()); else out[k]=(out[k]?(out[k]+" "+v.trim()):v.trim())};for(const raw of lines){const line=raw.trim();if(!line) continue;const m=line.match(/^([A-Za-z ]{2,30}):\s*(.*)$/);if(m){const key=m[1].toLowerCase().replace(/\s+/g,'_');const rest=m[2];current=key;if(rest) setField(key,rest);continue}if(/^[-*•]/.test(line)&&current){setField(current,line.replace(/^[-*•]\s?/,""))}else if(current){setField(current,line)}else{setField("task",line)}}return out}
function jsonToPrompt(j){let o;try{o=JSON.parse(j)}catch(e){throw new Error("Invalid JSON.")}const b=[];if(o.title) b.push(`TITLE: ${o.title}`);if(o.role||o.system) b.push(`ROLE: ${o.role||o.system}`);if(o.goal) b.push(`GOAL: ${o.goal}`);if(o.task||o.objective) b.push(`TASK: ${o.task||o.objective}`);const inputs=o.inputs||o.data;if(inputs){if(Array.isArray(inputs)){b.push("INPUTS:");inputs.forEach((v)=>b.push(`- ${v}`))}else if(typeof inputs==='object'){b.push("INPUTS:");for(const k of Object.keys(inputs)){b.push(`- ${k.toUpperCase()}: ${typeof inputs[k]==='string'?inputs[k]:JSON.stringify(inputs[k])}`)}}else{b.push(`INPUTS: ${inputs}`)}}if(o.steps&&Array.isArray(o.steps)&&o.steps.length){b.push("STEPS:");o.steps.forEach((s,i)=>b.push(`${i+1}. ${s}`))}if(o.constraints&&o.constraints.length){b.push("CONSTRAINTS:");o.constraints.forEach((c)=>b.push(`- ${c}`))}if(o.tone) b.push(`TONE: ${o.tone}`);if(o.style) b.push(`STYLE: ${o.style}`);if(o.output_format) b.push(`OUTPUT FORMAT: ${o.output_format}`);if(o.deliverables) b.push(`DELIVERABLES: ${typeof o.deliverables==='string'?o.deliverables:JSON.stringify(o.deliverables,null,2)}`);if(o.examples&&o.examples.length){b.push("EXAMPLES:");o.examples.forEach((ex)=>b.push(`- ${typeof ex==='string'?ex:JSON.stringify(ex)}`))}if(o.prompt){b.push("");b.push("ORIGINAL PROMPT:");b.push(o.prompt)}return b.join("\n")}
function setTab(active){const isAI=active==='ai';$('tab-heuristic').classList.toggle('active',!isAI);$('tab-ai').classList.toggle('active',isAI);$('aiNotice').classList.toggle('hidden',!isAI)}
$('tab-heuristic').addEventListener('click',()=>setTab('heuristic'));$('tab-ai').addEventListener('click',()=>setTab('ai'));
$('toJsonBtn').addEventListener('click',()=>{const txt=$('inputText').value.trim();const schema=$('schemaSelect').value;if(!txt){$('outputText').value="";return}const fn=heuristicSchemas[schema]||heuristicSchemas.default;$('outputText').value=fn(txt)});
$('toPromptBtn').addEventListener('click',()=>{const txt=$('inputText').value.trim();if(!txt){$('outputText').value="";return}try{$('outputText').value=jsonToPrompt(txt)}catch(e){alert(e.message)}});
$('copyBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('outputText').value)}catch(e){console.error(e)}});
$('saveBtn').addEventListener('click',()=>{const blob=new Blob([$('outputText').value],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='output.txt';a.click();URL.revokeObjectURL(url)});
async function runOpenAI(direction,inputText,model){const {apiKey}=await chrome.storage.sync.get(['apiKey']);if(!apiKey) throw new Error('No API key set. Go to Options.');const sys=direction==='tojson'?'You convert natural-language prompts into a clean, well-structured JSON. Be strict JSON.':'You convert JSON prompt specs into a concise, human-readable GPT prompt. Return plain text.';const userMsg=direction==='tojson'?`Convert this prompt to JSON. Be concise.\n\nPROMPT:\n${inputText}`:`Convert this JSON to a clean, human-readable prompt:\n\nJSON:\n${inputText}`;const resp=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${apiKey}`},body:JSON.stringify({model:model||"gpt-4o-mini",messages:[{role:"system",content:sys},{role:"user",content:userMsg}],temperature:0.2})});if(!resp.ok){const t=await resp.text();throw new Error(`API error: ${resp.status} ${t}`)}const data=await resp.json();const out=data.choices?.[0]?.message?.content||"";return out}
$('runAiBtn')?.addEventListener('click',async()=>{try{$('runAiBtn').disabled=true;const txt=$('inputText').value.trim();if(!txt) return;const out=await runOpenAI($('aiMode').value,txt,$('model').value.trim());$('outputText').value=out.trim()}catch(e){alert(e.message)}finally{$('runAiBtn').disabled=false}});
